### PR TITLE
samgeo v0.10.3

### PR DESCRIPTION
**Pull request by giswqs**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
You must rerender after making mods to yum requirements

**Comment by giswqs** [comment]
@hmaarrfk I was able to resolve the issue after adding the following. Thank you the information you provided on the opencv feedstock. 

```yml
  requires:
    - pip
    - libopencv *=headless*  # [linux]
 ```

**Comment by hmaarrfk** [comment]
I understand. But you shouldn't need both fixes. Only one or the other. You should be able to delete the yum requirements file and rerender. Or remove the test constraint.

**Comment by giswqs** [comment]
@hmaarrfk Thank you for clarifying. I have opened a new PR https://github.com/conda-forge/segment-geospatial-feedstock/pull/28. `mesa-libGL` had been added a long time ago before this issue. Should I keep or remove it?

**Comment by hmaarrfk** [comment]
It was added for qt5+opencv. Now that you are testing against headless you can remove it too

**Pull request merged**
